terraform-community-modules/tf_aws_vpc

README.md, main.tf, variables.tf
In order to support private DNS in the VPC both `enable_dns_support` and `enable_dns_hostnames` need to be set. PR #5 only sets `enable_dns_hostnames` so submitting this as well :-)
=> add enable_dns_support and enable_dns_hostnames to vpc

main.tf, variables.tf
A couple of small changes to make subnets optional. The first improves the count line, with the addition of compact(). (As discussed in https://github.com/hashicorp/terraform/issues/1604#issuecomment-155567822)
The second adds a default value to the variables to allow them to be made optional.
=> Make subnets optional

README.md, outputs.tf
As per the previous pull request, but adding public route tables too.
I didnt want to address the issues in your comment on the other PR @antonbabenko, i feel they are out of scope of this.
I simply want to access the outputs of the created resources.
=> Add public & private routes to outputs

README.md, main.tf, variables.tf
Summary of Changes
This adds a new variable for `map_public_ip_on_launch`, with a default value of `true`. Having this variable allows users to toggle on/off the auto-assign public IP setting in their VPC. Currently the value is just static.
If you auto assign an IP address, the elastic IP is attached to the instance, when the instance is terminated, the elastic IP is released.
There is use cases where people may want to put an instance in a public subnet, but not auto-assign a public IP, as they may want to consciously assign a specific Elastic IP, not lose that Elastic IP when the instance is terminated, etc.
=> Add Toggle Variable for map_public_ip_on_launch

main.tf
Summary of Changes:
Internet Gateway is something that can be tagged with a name, I think it would be worth tagging it similar to the public/private route tables, eg. myvpc-igw.
Visually it's faster/easier to look at a list and know what internet gateway is associated with a VPC
=> Add a Tag for Name to Internet Gateway

main.tf
oops, my previous patch created a configuration with invalid NAT Gateway
placement; fixed now
=> bugfix: create NAT Gateway in public, not private subnet

README.md, main.tf, variables.tf
Allow caller to pass additional tags to be added to all resources.  e.g. this can be used to add a tag defining the environment.
Usage is like:
```
module "vpc" {
source = "git@github.com:typerlc/tf_aws_vpc.git?ref=add_tags_variable"
name   = ...
cidr      = ...
azs       = ...
private_subnets = ...
public_subnets  = ...
tags {
"Terraform" = "true"
"Environment" = "${var.environment}"
}
}
```
=> Add tags variable

main.tf
The old version indexed directly on the var.azs array, but this won't wrap around if more than 1 subnet was defined for each AZ.  Using "elements" fixes this.
=> Handle multiple subnets per AZ

README.md, outputs.tf
I'm not 100% sure if this is the right way to do it, but I need to use the NAT gateways public elastic IPs as a source address in a security group rule and this is the only way I can get hold of them (or at least I could not figure out any other way).
=> Adding the NAT gateways public elastic IPs to the output

README.md, main.tf, outputs.tf, variables.tf
When building a VPC you may require to add RDS instances into your infrastructure. This might require isolated private subnet groups apart from the existing ones. Below are the changes introduced by this PR.
- Add the RDS private database subnets
- Create RDS subnet group
- Associate the subnets with private route tables
- Provide output for the following:
- A list of database subnet ids
- The id of the subnet group
```hcl
module "vpc" {
...
database_subnets   = ["10.0.90.0/24", "10.0.91.0/24", "10.0.92.0/24"]
....
}
```
Terraform will only provision these resources only when the variable `database_subnets` is provided.
=> feature(rds): add rds database subnets

README.md, main.tf, outputs.tf, variables.tf
Changes introduces by this PR
When building a VPC you may require to add Elasticache instances into your infrastructure. This might require isolated private subnet groups apart from the existing ones. Below are the changes introduced by this PR.
- Add the elasticache private elasticache subnets
- Create elasticache subnet group
- Associate the subnets with private route tables
Provide output for the following:
- A list of elasticache subnet ids
- The id of the elasticache subnet group
usage
```
module "vpc" {
...
elasticache_subnets   = ["10.0.90.0/24", "10.0.91.0/24", "10.0.92.0/24"]
....
}
```
Terraform will only provision these resources only when the variable elasticache_subnets is provided.
=> add elasticache / elasticache group creation as an option

main.tf
was getting 
```
> terraform plan
1 error(s) occurred:
* module.tf_aws_vpc.aws_elasticache_subnet_group.elasticache: : invalid or unknown key: tags
```
looks like tags are not a valid argument - https://www.terraform.io/docs/providers/aws/r/elasticache_subnet_group.html
=> remove tags from aws_elasticache_subnet_group stanza

main.tf
I was using this module for a project that had 9 private subnets and was frustrated when I found I also had 9 NAT gateways.
This change will create one NAT gateway per AZ and the private subnets will end up with routes to the NAT gateway in the same AZ.
This is related to issue #42
=> Adjusted count of NAT gateways to be dependent upon the number of AZs

main.tf
By adding a static "Tier" tag, this should make using the TF subnet_ids
data source easier to use with this module.
See https://www.terraform.io/docs/providers/aws/d/subnet_ids.html
With this comment, it should make it easier to preform this action and retrieve lists of subnet id's that can then be passed into other resources as needed.  
```HCL
data "aws_subnet_ids" "private" {
vpc_id = "${var.vpc_id}"
tags {
Tier = "private"
}
}
```
=> Adding a Tier tag to all subnets

main.tf, variables.tf
* Added var.public_subnet_tags
* Added var.private_subnet_tags
* Added var.database_subnet_tags
* Added var.elasticache_subnet_tags
This helps solve a specific issue with Kubernetes, where public &
private subnets must be appropriately tagged for public/private ELBs to
work.
=> Support subnet-specific additional tags

README.md, main.tf, variables.tf
I'm exposing the VPC resource argument `instance_tenancy` as a variable.
=> Adding tenancy option for instances launched into the VPC

main.tf
this change gives subnets consistent names in the format environment-subnet-type-az
it is basically cosmetic, and makes things easier to figure out in the web console
=> give subnets consistent names

main.tf
Prior to this change, **only this input value** would create NAT gateways:
```
module "vpc" {
source = "github.com/terraform-community-modules/tf_aws_vpc"
enable_nat_gateway = "true"
...
}
```
After this change, **any of these input values** will create NAT gateways:
```
module "vpc" {
source = "github.com/terraform-community-modules/tf_aws_vpc"
enable_nat_gateway = "true"
enable_nat_gateway = "1"
enable_nat_gateway = true
enable_nat_gateway = 1
...
}
```
...and conversly these will not create any NAT gateways:
```
module "vpc" {
source = "github.com/terraform-community-modules/tf_aws_vpc"
enable_nat_gateway = "false"
enable_nat_gateway = "0"
enable_nat_gateway = false
enable_nat_gateway = 0
...
}
```
=> 🐛 #47  Fix issue with string vs bool value with enable_nat_gateway input

README.md, main.tf, variables.tf
~**DEPENDENT ON PR #57**~ (*merged*)
* You have 2 public subnets
* You have 2 private subnets
Prior to this change when you set `enable_nat_gateway=true` you would get the following infrastructure:
* 2 EIPs (_1 per private subnet_)
* 2 NAT Gateway (_1 per private subnet_)
While this follows high availability best practices and _should be_ your configuration in a production, sometimes you don't want to incur the cost of having multiple NAT gateways in your dev and testing environments.
After this change when you set `enable_nat_gateway=true` and `single_nat_gateway=true` you would get the following infrastructure:
* 1 EIP (_1 total_)
* 1 NAT Gateway (_1 total_)
Meaning that you share a single EIP/NAT gateway pairing across all of your private subnets. Reducing costs while maintaining …
=> ✨ #42 Add support for provisioning only a single NAT Gateway

outputs.tf
I've been peering VPCs and I needed this one in to facilitate some cross-VPC routing rules.
There might be some other use of this output in the long run.
=> Add vpc_cidr_block output

outputs.tf
As it has no data resource to acquire it independently form the VPC resource it is good it is returned in an output.
=> Add default_network_acl_id output

README.md, main.tf, variables.tf
Tried to combine this module with https://github.com/terraform-community-modules/tf_aws_rds - noticed that there are two db_subnet_group resources created.
Added an extra control switch to resolve the issue.
=> Added variable to control if db_subnet_group should be created.
